### ISSUE TITLE
Add all three sites to Atmospheric tab

### ISSUE THREAD

**Issue by UArizonaCampusLivingLabforGSI** [UArizonaGSICampusLivingLab/gsi-dashboard#12]
Update the Atmospheric tab to include check boxes for looking at multiple sites at the same time. Have sites differentiated by line color.

**Comment by Aariq** [comment]
I think the idea was to have sites differentiated by color and then things like basin/non-basin or vapor pressure/vpd differentiated by linetype.  I'll play around with it and see what works best though.
