### ISSUE TITLE
Put value boxes back *somewhere*

### ISSUE THREAD

**Issue by UArizonaCampusLivingLabforGSI** [UArizonaGSICampusLivingLab/gsi-dashboard#13]
Test moving the value bar to the sidebar.

**Comment by Aariq** [comment]
If they don't fit well in sidebar or elsewhere, they might be good in a "home" tab along with some text describing the project and linking to the homepage.

**Comment by Aariq** [comment]
For value boxes:

- Air temp: most recent value for each location
- Soil temp: same
- Precip: date of last rain and how much?  or cumulative (since the start of the year) for each site.
