### ISSUE TITLE
Plot calculated variables

### ISSUE THREAD

**Issue by Aariq** [UArizonaGSICampusLivingLab/gsi-dashboard#21]
- [x] Evapotranspiration
- [x] Plant-available water
- [x] Heat/comfortability index

Need to figure out what models/calculations to use and make the plots.

**Comment by UArizonaCampusLivingLabforGSI** [comment]
From Zentra

Plant available water (https://www.metergroup.com/en/meter-environment/measurement-insights/how-model-plant-available-water)
Available water content = field capacity - plant wilting point
Plant Available Water = (Volumetric Water Content - Plant Wilting Point) / Available Water Content

Evapotranspiration (https://docs.zentracloud.com/l/en/article/zlpd1t7hk2-evapotranspiration) and refenerces the Penman-Monteith equation:
https://www.fao.org/3/x0490e/x0490e06.htm#chapter%202%20%20%20fao%20penman%20monteith%20equation

@MJBarrios will share example files from the output on zentra although they do not look helpful.

**Comment by Aariq** [comment]
If it's Penman-Monteith for ET, I'm pretty sure I have code laying around somewhere to calculate this and we have all the data we need.  For plant available water, it seems like theres some guestimation to be done, right? I wonder what values they are using for field capacity and plant wilting point 🤔

**Comment by Aariq** [comment]
Plant available water is something @jessicaguo might be able to help with.

**Comment by Aariq** [comment]
What is the time resolution for the evapotranspiration?  The `penman()` function in the `SPEI` package calculates ET using monthly averages of variables.  Is that what we want? https://sbegueria.r-universe.dev/SPEI/doc/manual.html#Potential-evapotranspiration

**Comment by Aariq** [comment]
Let's use this issue to discuss what is *displayed* in the app.  I've opened another issue in the data wrangling repo to discuss accessing the data via REST API: https://github.com/UArizonaGSICampusLivingLab/gsi-wrangling-workflow/issues/23

**Comment by Aariq** [comment]
New plan is to get RH instead of vapor pressure, so I can also change the vp/vpd plot to RH instead
